# Generated by Django 5.0.3 on 2024-03-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathroomAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_name', models.CharField(max_length=100)),
                ('appliance_name', models.CharField(max_length=100)),
                ('wattage', models.IntegerField(help_text='Wattage in Watts')),
                ('quantity', models.IntegerField(default=1)),
                ('jan_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('feb_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mar_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('apr_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('may_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('jun_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('jul_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('aug_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sep_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('oct_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nov_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dec_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
