# Generated by Django 5.0.3 on 2024-03-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_dininghallappliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingroomAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=100)),
                ('wattage', models.IntegerField(help_text='Wattage in Watts')),
                ('quantity', models.IntegerField(default=1)),
                ('jan', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('feb', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mar', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('apr', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('may', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('jun', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('jul', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('aug', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sep', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('oct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nov', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dec', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
