# Generated by Django 5.0.3 on 2024-03-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_livingroomappliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininghallappliance',
            name='dininghall_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kitchenappliance',
            name='kitchen_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='livingroomappliance',
            name='livingroom_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
