# Generated by Django 5.0.3 on 2024-03-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_bathroomappliance_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathroomappliance',
            name='user_profile',
        ),
    ]
